Repository twenty-three-23/peech-flutter, pull requests merged in 2024-10, with the labels that each got.

#237 TT-455 바텀 네비게이션 적용하기
  lib/features/common/widgets/common_scaffold.dart
  lib/features/common/widgets/custom_bottom_navigation.dart
  lib/features/practice_history/controller/history_controller.dart
  lib/features/root/view/root_screen.dart
  lib/routers/routers.dart
Labels: 기능구현, ui

#240 interview question
  lib/features/common/widgets/common_text_field.dart
  lib/features/interview_question/controller/interview_question_input_controller.dart
  lib/features/interview_question/data_source/remote/remote_interview_question_data_source.dart
  lib/features/interview_question/model/interview_questions_list_model.dart
  lib/features/interview_question/model/interview_script_model.dart
  lib/features/interview_question/view/interview_question_input_screen.dart
  lib/features/interview_question/view/interview_question_result_screen.dart
  lib/routers/routers.dart
Labels: 기능구현

#242 TT-458 스플래시 및 온보딩 구현
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/values-night/styles.xml
  android/app/src/main/res/values/styles.xml
  assets/images/onboarding/onboarding_image_1.png
  assets/images/onboarding/onboarding_image_2.png
  assets/images/onboarding/onboarding_image_3.png
  assets/images/onboarding/onboarding_progress_1.png
  assets/images/onboarding/onboarding_progress_2.png
  assets/images/onboarding/onboarding_progress_3.png
  assets/images/onboarding/onboarding_text_1.png
  assets/images/onboarding/onboarding_text_2.png
  assets/images/onboarding/onboarding_text_3.png
  assets/images/splash_screen_image.png
  assets/images/splash_screen_image_android12.png
  flutter_native_splash.yaml
  ios/Runner/AppDelegate.swift
  ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png
  ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  ios/Runner/Info.plist
  lib/features/common/data_source/local/local_user_info_storage.dart
  lib/features/common/widgets/colored_button.dart
  lib/features/common/widgets/show_common_dialog.dart
  lib/features/home/view/home_screen.dart
  lib/features/onboarding/controller/onboarding_controller.dart
  lib/features/onboarding/view/onboarding_screen.dart
  lib/features/practice_history/view/history_major_detail_screen.dart
  lib/features/practice_history/widgets/history_list_view.dart
  lib/features/practice_result/view/practice_result_screen.dart
  lib/features/root/view/root_screen.dart
  lib/features/script_input/view/script_expected_time_screen.dart
  lib/features/script_input/view/script_input_screen.dart
  lib/features/theme_input/view/theme_input_screen.dart
  lib/features/voice_recode/view/voice_recode_screen_no_script.dart
  lib/features/voice_recode/view/voice_recode_screen_with_script.dart
  lib/initialization/app_initializer.dart
  lib/initialization/initializers/firebase_initializer.dart
  lib/initialization/initializers/global_controllers_initializer.dart
  lib/initialization/initializers/kakao_sdk_initializer.dart
  lib/initialization/initializers/local_storage_initializer.dart
  lib/initialize/app_initializer.dart
  lib/main.dart
  lib/routers/routers.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: 기능구현, ui

#243 TT-466 practice result design
  lib/features/common/widgets/common_scaffold.dart
  lib/features/interview_question/controller/interview_question_input_controller.dart
  lib/features/practice_result/controller/practice_result_controller.dart
  lib/features/practice_result/model/paragraph_list_model.dart
  lib/features/practice_result/model/paragraph_model.dart
  lib/features/practice_result/view/practice_result_screen.dart
Labels: 기능구현, ui

#251 TT-456 히스토리 뷰 1차 제작
  lib/features/practice_history/view/history_view.dart
Labels: ui

#253 TT-467 마이페이지 연결
  lib/features/common/controllers/review_controller.dart
  lib/features/common/platform/platform_device_info/device_info_on_mobile.dart
  lib/features/common/platform/platform_device_info/device_info_on_web.dart
  lib/features/common/platform/platform_device_info/platform_device_info.dart
  lib/features/home/controller/home_controller.dart
  lib/features/mypage/controller/mypage_controller.dart
  lib/features/mypage/view/mypage_screen.dart
  lib/features/mypage/widget/app_version_button.dart
  lib/features/mypage/widget/mypage_item_button.dart
  lib/features/practice_history/controller/history_controller.dart
  lib/features/root/view/root_screen.dart
  lib/routers/routers.dart
Labels: 기능구현, ui, 디자인

#255 TT-472 자잘한 오류들 수정
  lib/features/common/controllers/social_login_controller.dart
  lib/features/common/controllers/user_info_controller.dart
  lib/features/common/platform/platform_device_info/device_info_on_mobile.dart
  lib/features/common/platform/platform_device_info/device_info_on_web.dart
  lib/features/common/platform/platform_device_info/platform_device_info.dart
  lib/features/home/controller/home_controller.dart
  lib/features/home/view/home_screen2.dart
  lib/features/interview_question/view/interview_question_input_screen.dart
  lib/features/interview_question/view/interview_question_result_screen.dart
  lib/features/onboarding/view/onboarding_screen.dart
  lib/features/script_input/view/script_expected_time_screen.dart
  lib/features/script_input/view/script_input_screen.dart
Labels: 버그, 리팩토링, ui, 디자인

#252 TT-468 history api
  lib/features/home/view/home_screen2.dart
  lib/features/practice_history/controller/history_controller.dart
  lib/features/practice_history/data_source/remote/remote_major_list_data_source.dart
  lib/features/practice_history/model/default_script_list_model.dart
  lib/features/practice_history/model/default_script_model.dart
  lib/features/practice_history/view/history_view.dart
  lib/features/root/view/root_screen.dart
  lib/routers/routers.dart
Labels: api, ui

#257 TT-474 기록에 예상 면접질문 받아보기 연동
  lib/features/interview_question/controller/interview_question_input_controller.dart
  lib/features/interview_question/view/interview_question_input_screen.dart
  lib/features/practice_history/controller/history_controller.dart
  lib/features/practice_history/view/history_view.dart
Labels: 기능구현, ui

#259 TT-476 기록, 마이페이지, 홈 디자인 수정
  lib/features/home/view/home_screen2.dart
  lib/features/mypage/view/mypage_screen.dart
  lib/features/mypage/widget/app_version_button.dart
  lib/features/mypage/widget/mypage_item_button.dart
  lib/features/practice_history/controller/history_controller.dart
  lib/features/practice_history/view/history_view.dart
Labels: 버그, 수정, ui, 디자인

#260 TT-476 기록, 마이페이지, 홈 디자인 수정
  lib/features/mypage/view/mypage_screen.dart
Labels: 수정, ui, 디자인

#262 TT-475 결과 화면에서 수정하기 기능 제거
  lib/features/interview_question/controller/interview_question_input_controller.dart
  lib/features/practice_history/view/history_view.dart
  lib/features/practice_result/view/practice_result_screen.dart
Labels: 수정, ui

#264 TT-469 apple
  ios/Runner/Info.plist
  lib/features/common/controllers/social_login_controller.dart
  lib/features/common/widgets/social_getting_additional_info_view.dart
  lib/features/common/widgets/social_login_choice_view.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: 수정, ui

#266 TT-490 기록에 분석 보기 구현
  lib/features/practice_history/controller/history_controller.dart
  lib/features/practice_history/data_source/remote/remote_practice_result_data_source.dart
  lib/features/practice_history/model/paragraph_list_model.dart
  lib/features/practice_history/model/paragraph_model.dart
  lib/features/practice_history/view/history_detail.dart
  lib/features/practice_history/view/history_view.dart
  lib/features/practice_result/controller/practice_result_controller.dart
  lib/features/practice_result/model/now_status.dart
  lib/features/practice_result/model/paragraph_list_model.dart
  lib/features/practice_result/model/paragraph_model.dart
  lib/features/practice_result/model/req_paragraph_list_model.dart
  lib/features/practice_result/view/practice_result_screen.dart
  lib/routers/routers.dart
Labels: 기능구현, api, ui
